### ISSUE TITLE
Make use of thirdpartylibs.xml

### ISSUE THREAD

**Issue by mudrd8mz** [fredcy/moodle-tool_datatables#1]
Please see 

https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

Among other things, locations defined in this file are excluded from the coding style prechecks that are executed during the plugin validation.

**Comment by fredcy** [comment]
https://github.com/fredcy/moodle-tool_datatables/commit/fb6711c7f03dd5ddc0625c6bb4752cf0d59425f4 moves thirdpartylibs.xml to the plugin root and adds some missing libraries to the included list.
I published new version v0.3 with that change.
